name = "MQTT"
uuid = "7b5fea6c-6225-4b7d-8f4a-8782848a6463"
authors = ["McCoy R. Becker <mccoybecker@gmail.com>"]
version = "0.1.0"

[deps]
Dagger = "d58978e5-989f-55fb-8d15-ea34adc7bf54"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
MemPool = "f9f48841-c794-520a-933b-121f7ba6ed94"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
